name: spare_scores test cases on macos

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: "macos-latest"

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            pthon-version: '3.8'
        - name: Set-up miniconda for macos
          uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: 3.8
              miniconda-version: "latest"
        - name: Create conda env
          run: conda create -n spare python=3.8
        - name: Activate conda env
          run: echo "conda activate spare" >> $GITHUB_ENV
        - name: Install pip
          run: conda run -n spare conda install pip
        - name: Install spare scores
          run: conda run -n spare pip install spare_sores
        - name: Run unit tests
          run: |
            cd tests/unit && python -m unittest discover -s . -p "*.py"
