name: MacOS python=3.12

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ["macos-13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
      - name: Install spare scores
        run: |
          pip install setuptools twine wheel pytest pytest-cov
          python -m pip install .
      - name: Run unit tests
        run: |
          cd tests/unit && pytest --cov=../../
