name: ubuntu build python=3.9

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install spare scores
        run: |
          python -m pip cache purge
          pip install -r requirements.txt
          pip install setuptools twine wheel
          python setup.py bdist_wheel
          cd dist
          WHEEL_FILE=$(ls spare_scores*)
          pip install "$WHEEL_FILE"
      - name: Run unit tests
        run: |
          cd tests/unit && python -m unittest discover -s . -p "*.py"
