name: spare_scores test cases on ubuntu for python 3.12

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set-up miniconda for macos and ubuntu
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12
          miniconda-version: "latest"
      - name: Create conda env
        run: conda create -n spare python=3.12
      - name: Install pip
        run: conda run -n spare conda install pip
      - name: Install spare scores
        run: |
          pip install setuptools twine wheel
          python -m pip install .
      - name: Download dependencies
        run: pip install setuptools && pip install .
      - name: Run unit tests
        run: |
          cd tests/unit && python -m unittest discover -s . -p "*.py"
