name: spare_scores test cases on ubuntu 

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ["ubuntu-latest"]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            pthon-version: '3.8'
        - name: Set-up miniconda for macos and ubuntu
          uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: 3.8
              miniconda-version: "latest"
        - name: Create conda env
          run: conda create -n spare python=3.8
        - name: Install pip
          run: conda run -n spare conda install pip
        - name: Install spare scores
          run: conda run -n spare pip install spare_scores
        - name: Download dependencies
          run:  pip install setuptools && pip install .
        - name: Run unit tests
          run: |
            cd tests/unit && python -m unittest discover -s . -p "*.py"
